# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    currency.class: AppBundle\Service\CurrencyService

services:
#    currency:
#        class: %currency.class%
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    onconnect.listener:
        class: src\AppBundle\EventListener\OnConnect
        tags:
             - { name: doctrine.event_listener, event: postConnect }