<?php

namespace MeVisa\ERPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductsRepository extends EntityRepository
{

    public function findWithMessages()
    {
        return $this->createQueryBuilder("op")
                ->select("op, om, o")
                ->join('op.messages', 'om')
                ->join('op.orderRef', 'o')
                ->orderBy('o.number', 'ASC')
                ->getQuery()
                ->getResult();
    }

}