<?php

namespace MeVisa\ERPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductsRepository extends EntityRepository
{

    public function findingNemo()
    {
        return $this->createQueryBuilder('opr')
                        ->select('opr, o, p')
                        ->leftJoin('opr.orderRef', 'o')
                        ->leftJoin('opr.product', 'p')
                        ->where("o.wcId IS NOT NULL")
                        ->orderBy('o.id', 'ASC')
//                        ->setMaxResults(100)
                        ->getQuery()
                        ->getResult();
    }

}
