services:

    erp.order:
        class:  MeVisa\ERPBundle\Service\OrderService
        arguments: [ '@doctrine.orm.entity_manager', '@templating', '@security.token_storage' ]

    erp.wcorder:
        class:  MeVisa\ERPBundle\Service\WCOrderService
        arguments: [ '@doctrine.orm.entity_manager' ]
