parameters:
    currency.class: AppBundle\Service\CurrencyService
    statusCSS.class: AppBundle\Service\StatusCSSService

services:
    onconnect.listener:
        class: AppBundle\EventListener\OnConnect
        tags:
            - { name: doctrine.event_listener, event: postConnect }

    app.currency:
        class:  %currency.class%
        arguments: [@doctrine.orm.entity_manager]

    app.statusCSS:
        class:  %statusCSS.class%