<?php

namespace MeVisa\CRMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends EntityRepository
{

    public function findLikeName($name)
    {
        return $this->createQueryBuilder('c')
                        ->select('c, c.name as value')
                        ->where("c.name LIKE ?1")
                        ->setParameter('1', "%" . $name . "%")
                        ->getQuery()
                        ->getArrayResult();
    }

}
